# Generated by Django 3.1.3 on 2020-11-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='date_update',
            new_name='date_updated',
        ),
    ]
